### ISSUE TITLE
How to generate restoreId in flutter fresh chat(getting empty string)?

### ISSUE THREAD

**Issue by chaitanya-y** [fayeed/flutter_freshchat#25]
I checked some issues online.someone mentioned that restoreId will get generated only after first was sent.I tried to call send message function and then did identify user .Still, I am getting restoreId as empty string.

      FreshchatUser user = FreshchatUser.initail();
      user.email = email;
      user.firstName = firstName;
      user.lastName = lastName;
      user.phoneCountryCode = '91';
      user.phone = phone;
      bool result = await FlutterFreshchat.updateUserInfo(user: user);
      bool sendMessageSuccess =await FlutterFreshchat.send(message: 'Hello',tag: 'test');
      if(sendMessageSuccess){
      freshChatId = await FlutterFreshchat.identifyUser(externalID: phone, restoreID: null);
      print('freshChatId');
       }
      
and
2)Is there any way to trigger an event on the click of back button in the flutter chat screen.

**Comment by fayeed** [comment]
@chaitanya-y I have not been able to reproduce this issue I don't what the reason is, there is already an open issue #11 you can try there also if this package doesn't work for you there is also one more package [freshchat](https://github.com/archie-sh/freshchat) Its a forked repository of this repository.

Also one more thing please don't spam other issues if you don't receive a reply.

**Comment by fayeed** [comment]
@chaitanya-y You could also check [this](https://github.com/freshdesk/freshchat-ios/issues/85#issuecomment-582431940).

**Comment by fayeed** [comment]
@chaitanya-y you can also check this [issue](https://github.com/freshdesk/freshchat-ios/issues/85#issuecomment-582431940)
